version: '3.9'

services:
  app:
    build: .
    container_name: smartshop-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/smartshop_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 202580
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres

  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: smartshop_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 202580
    ports:
      - '5432:5432'
